name: Test Build Deploy

on:
    push:
        branches:
        - 'main'
    pull_request:
        branches:
        - 'main'
    workflow_dispatch:

concurrency:
  group: "test-build-deploy"
  cancel-in-progress: true

jobs:
    test:
        name: Test
        runs-on: ubuntu-slim
        steps:
            - name: Setup Node Project
              uses: ./.github/actions/setup-node-project
            - name: Run test
              run: npm test

    build:
      name: Build
      runs-on: ubuntu-slim
      needs: test
      outputs:
        build-artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
      steps:
        - name: Setup Node Project
          uses: ./.github/actions/setup-node-project
        - name: Create build
          run: npm run build
        - name: Upload build
          id: artifact-upload-step
          uses: actions/upload-artifact@v7
          with:
            name: build-artifact
            path: './dist'

    deploy:
      name: Deploy
      runs-on: ubuntu-slim
      needs: build
      if: github.event_name == 'push'
      permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
      environment:
        name: production
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Get the artifact from build step
          uses: actions/download-artifact@v8
          with:
            artifact-ids: ${{needs.build.outputs.build-artifact-id}}
            path: './dist'
        - name: Setup Pages
          uses: actions/configure-pages@v6
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v5
          with:
            path: './dist'
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v5